# Copyright 2023 Nick Anderegg
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
# OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

name: Build and Release Obsidian Plugin

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

env:
  PLUGIN_SLUG: obsidian-ulid-plugin

concurrency:
  group: build-plugin
  cancel-in-progress: true

jobs:
  build:
    name: Build the plugin
    runs-on: ubuntu-latest

    steps:
      - id: checkout-branch
        name: Checkout branch
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - id: setup-node
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - id: install-npm-deps
        name: Install npm dependencies
        run: npm install

      - id: npm-build-plugin
        name: Build plugin with npm
        run: npm run build

      - id: zip-build-dir
        name: Package plugin build directory
        run: |
          mkdir ${{ env.PLUGIN_SLUG }}
          cp main.js manifest.json ${{ env.PLUGIN_SLUG }}
          zip -r ${{ env.PLUGIN_SLUG }}.zip ${{ env.PLUGIN_SLUG }}
          ls -lAh

      # Save the build artifacts for this workflow run
      - id: store-build
        name: Store build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.PLUGIN_SLUG }}
          path: ${{ env.PLUGIN_SLUG }}.zip


