# Copyright 2023 Nick Anderegg
#
# Permission to use, copy, modify, and/or distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT
# OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

name: Build and Release Obsidian Plugin

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
  workflow_dispatch:

env:
  PLUGIN_SLUG: obsidian-ulid-plugin

concurrency:
  group: build-plugin
  cancel-in-progress: true

jobs:
  build-plugin:
    name: Build the plugin
    runs-on: ubuntu-latest

    steps:
      - id: checkout-branch
        name: Checkout branch
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - id: setup-node
        name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: npm

      - id: install-npm-deps
        name: Install npm dependencies
        run: npm install

      - id: npm-build-plugin
        name: Build plugin with npm
        run: npm run build

      - id: zip-build-dir
        name: Package plugin build directory
        run: |
          export PLUGIN_DIR=${GITHUB_WORKSPACE}/${{ env.PLUGIN_SLUG }}
          mkdir ${PLUGIN_DIR}
          cp main.js manifest.json ${PLUGIN_DIR}
          cd ${PLUGIN_DIR}
          tar -cvf ${GITHUB_WORKSPACE}/${{ env.PLUGIN_SLUG }}.tar .
          ls -lAh

      # Save the build artifacts for this workflow run
      - id: store-build
        name: Store build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: plugin-build
          path: ${{ env.PLUGIN_SLUG }}.tar

  release-plugin:
    name: Release the plugin
    runs-on: ubuntu-latest
    needs: [build-plugin]
    concurrency:
      group: release-plugin-to-gh
      cancel-in-progress: false

    steps:
      - id: download-build
        name: Download plugin build artifacts
        uses: actions/download-artifact@v3
        with:
          name: plugin-build

      - id: untar-build-dir
        name: Untar plugin build directory
        run: |
          export PLUGIN_DIR=${GITHUB_WORKSPACE}/${{ env.PLUGIN_SLUG }}
          mkdir ${PLUGIN_DIR}
          cd ${PLUGIN_DIR}
          tar -xvf ${PLUGIN_DIR}.tar

      - id: zip-release-dir
        name: Zip plugin release directory
        run: |
          zip -r ${GITHUB_WORKSPACE}/${{ env.PLUGIN_SLUG }}.zip ${GITHUB_WORKSPACE}/${{ env.PLUGIN_SLUG }}
          ls -lAh

      - id: create-release
        name: Create release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ env.PLUGIN_SLUG }}.zip
            ${{ env.PLUGIN_SLUG }}/main.js
            ${{ env.PLUGIN_SLUG }}/manifest.json


